# Use an official Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Copy the rest of the app
COPY . .

# Build the app
RUN pnpm build

# Expose the app's port
EXPOSE 7007

# Start the app
CMD ["pnpm", "migrate"]
